package com.mani.payment_transfer_system.entity;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Transaction entity representing a transfer between two accounts.
 * Stores transaction history for audit and tracking purposes.
 */
@Entity
@Table(name = "transactions")
@Getter
@Setter
@NoArgsConstructor
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@ToString
public class Transaction {

    /**
     * The unique transaction identifier.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @EqualsAndHashCode.Include
    @Column(name = "id")
    private Long id;

    /**
     * The account ID from which the amount is transferred.
     */
    @Column(name = "source_account_id", nullable = false)
    private Long sourceAccountId;

    /**
     * The account ID to which the amount is transferred.
     */
    @Column(name = "destination_account_id", nullable = false)
    private Long destinationAccountId;

    /**
     * The amount transferred.
     * Precision: 19 digits, Scale: 5 decimal places.
     */
    @Column(name = "amount", nullable = false, precision = 19, scale = 5)
    private BigDecimal amount;

    /**
     * The timestamp when the transaction was created.
     * Automatically set on entity creation.
     */
    @Column(name = "timestamp", nullable = false)
    private LocalDateTime timestamp;

    /**
     * Constructs a new Transaction with the specified accounts and amount.
     * The timestamp is automatically set to the current time.
     *
     * @param sourceAccountId the account ID from which the amount is transferred
     * @param destinationAccountId the account ID to which the amount is transferred
     * @param amount the amount to transfer
     */
    public Transaction(Long sourceAccountId, Long destinationAccountId, BigDecimal amount) {
        this.sourceAccountId = sourceAccountId;
        this.destinationAccountId = destinationAccountId;
        this.amount = amount;
        this.timestamp = LocalDateTime.now();
    }

    /**
     * JPA lifecycle callback method.
     * Sets the timestamp to current time if not already set before persisting.
     */
    @PrePersist
    protected void onCreate() {
        if (timestamp == null) {
            timestamp = LocalDateTime.now();
        }
    }
}

